root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api-server"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["web", "tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = true
