run:
  timeout: 5m

linters:
  enable:
    - errcheck

linters-settings:
  errcheck:
    # Exclude test files from errcheck
    exclude-functions:
      - fmt.Sscanf

issues:
  exclude-rules:
    # Exclude test files from errcheck
    - linters:
        - errcheck
      path: _test\.go
