server:
  port: [0;34m[INFO][0m 请输入端口 (非交互式模式，使用默认值: [1;33m8080[0m)
8080
  host: 0.0.0.0

database:
  path: [0;34m[INFO][0m 请输入安装路径 (非交互式模式，使用默认值: [1;33m/opt/deploypilot[0m)
/opt/deploypilot/data/deploypilot.db

storage:
  data_dir: [0;34m[INFO][0m 请输入安装路径 (非交互式模式，使用默认值: [1;33m/opt/deploypilot[0m)
/opt/deploypilot/data
  logs_dir: [0;34m[INFO][0m 请输入安装路径 (非交互式模式，使用默认值: [1;33m/opt/deploypilot[0m)
/opt/deploypilot/logs
  backups_dir: [0;34m[INFO][0m 请输入安装路径 (非交互式模式，使用默认值: [1;33m/opt/deploypilot[0m)
/opt/deploypilot/backups

auth:
  jwt_secret: s0yaz77nmmdutys8rs9plts3w53i5pv9
