import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/login',
      name: 'Login',
      component: () => import('@/views/Login.vue'),
      meta: { guest: true },
    },
    {
      path: '/register',
      name: 'Register',
      component: () => import('@/views/Register.vue'),
      meta: { guest: true },
    },
    {
      path: '/status',
      name: 'StatusPage',
      component: () => import('@/views/StatusPage.vue'),
      meta: { guest: true, titleKey: 'routes.statusPage' },
    },
    {
      path: '/dashboard-tv',
      name: 'DashboardTV',
      component: () => import('@/views/DashboardTV.vue'),
      meta: { requiresAuth: true },
    },
    {
      path: '/',
      component: () => import('@/layout/MainLayout.vue'),
      meta: { requiresAuth: true },
      children: [
        {
          path: '',
          name: 'Dashboard',
          component: () => import('@/views/Dashboard.vue'),
          meta: { titleKey: 'routes.dashboard' },
        },
        {
          path: 'apps',
          name: 'Apps',
          component: () => import('@/views/Apps.vue'),
          meta: { titleKey: 'routes.apps' },
        },
        {
          path: 'apps/:id',
          name: 'AppDetail',
          component: () => import('@/views/AppDetail.vue'),
          props: true,
          meta: { titleKey: 'routes.appDetail' },
        },
        {
          path: 'apps/:id/logs',
          name: 'AppLogs',
          component: () => import('@/views/AppLogs.vue'),
          props: true,
          meta: { titleKey: 'routes.appLogs' },
        },
        {
          path: 'apps/:id/env',
          name: 'AppEnv',
          component: () => import('@/views/AppEnv.vue'),
          props: true,
          meta: { titleKey: 'routes.appEnv' },
        },
        {
          path: 'apps/:id/backups',
          name: 'AppBackups',
          component: () => import('@/views/AppBackups.vue'),
          props: true,
          meta: { titleKey: 'routes.appBackups' },
        },
        {
          path: 'servers',
          name: 'Servers',
          component: () => import('@/views/Servers.vue'),
          meta: { titleKey: 'routes.servers' },
        },
        {
          path: 'servers/:id',
          name: 'ServerDetail',
          component: () => import('@/views/ServerDetail.vue'),
          props: true,
          meta: { titleKey: 'routes.serverDetail' },
        },
        {
          path: 'servers/:id/terminal',
          name: 'ServerTerminal',
          component: () => import('@/views/ServerTerminal.vue'),
          props: true,
          meta: { titleKey: 'routes.serverTerminal' },
        },
        {
          path: 'servers/:id/environment',
          name: 'ServerEnvironment',
          component: () => import('@/views/ServerEnvironment.vue'),
          props: true,
          meta: { titleKey: 'routes.serverEnvironment' },
        },
        {
          path: 'deployments',
          name: 'Deployments',
          component: () => import('@/views/Deployments.vue'),
          meta: { titleKey: 'routes.deployments' },
        },
        {
          path: 'credentials',
          name: 'Credentials',
          component: () => import('@/views/Credentials.vue'),
          meta: { titleKey: 'routes.credentials' },
        },
        {
          path: 'dns',
          name: 'DNS',
          component: () => import('@/views/DNS.vue'),
          meta: { titleKey: 'routes.dns' },
        },
        {
          path: 'ssl',
          name: 'SSL',
          component: () => import('@/views/SSL.vue'),
          meta: { titleKey: 'routes.ssl' },
        },
        {
          path: 'providers',
          name: 'Providers',
          component: () => import('@/views/Providers.vue'),
          meta: { titleKey: 'routes.providers' },
        },
        {
          path: 'clusters',
          name: 'Clusters',
          component: () => import('@/views/Clusters.vue'),
          meta: { titleKey: 'routes.clusters' },
        },
        {
          path: 'registries',
          name: 'Registries',
          component: () => import('@/views/Registries.vue'),
          meta: { titleKey: 'routes.registries' },
        },
        {
          path: 'plugins',
          name: 'Plugins',
          component: () => import('@/views/Plugins.vue'),
          meta: { titleKey: 'routes.plugins' },
        },
        {
          path: 'batch',
          name: 'BatchOperations',
          component: () => import('@/views/BatchOperations.vue'),
          meta: { titleKey: 'routes.batch' },
        },
        {
          path: 'activity',
          name: 'ActivityFeed',
          component: () => import('@/views/ActivityFeed.vue'),
          meta: { titleKey: 'routes.activity' },
        },
        {
          path: 'cicd',
          name: 'CICD',
          component: () => import('@/views/CICD.vue'),
          meta: { titleKey: 'routes.cicd' },
        },
        {
          path: 'monitor',
          name: 'Monitor',
          component: () => import('@/views/Monitor.vue'),
          meta: { titleKey: 'routes.monitor' },
        },
        {
          path: 'monitor/containers',
          name: 'MonitorContainers',
          component: () => import('@/views/MonitorContainers.vue'),
          meta: { titleKey: 'routes.monitorContainers' },
        },
        {
          path: 'monitor/alerts',
          name: 'MonitorAlerts',
          component: () => import('@/views/MonitorAlerts.vue'),
          meta: { titleKey: 'routes.monitorAlerts' },
        },
        {
          path: 'monitor/alert-rules',
          name: 'MonitorAlertRules',
          component: () => import('@/views/MonitorAlertRules.vue'),
          meta: { titleKey: 'routes.monitorAlertRules' },
        },
        {
          path: 'monitor/uptime',
          name: 'UptimeMonitorsList',
          component: () => import('@/views/UptimeMonitors.vue'),
          meta: { titleKey: 'routes.uptimeMonitors' },
        },
        {
          path: 'monitor/heartbeats',
          name: 'HeartbeatsList',
          component: () => import('@/views/Heartbeats.vue'),
          meta: { titleKey: 'routes.heartbeats' },
        },
        {
          path: 'monitor/server/:id',
          name: 'MonitorServerDetail',
          component: () => import('@/views/MonitorServerDetail.vue'),
          props: true,
          meta: { titleKey: 'routes.monitorServerDetail' },
        },
        {
          path: 'monitor/alerts/:id',
          name: 'MonitorAlertDetail',
          component: () => import('@/views/MonitorAlertDetail.vue'),
          props: true,
          meta: { titleKey: 'routes.monitorAlertDetail' },
        },
        {
          path: 'monitor/settings',
          name: 'MonitorSettings',
          component: () => import('@/views/MonitorSettings.vue'),
          meta: { titleKey: 'routes.monitorSettings' },
        },
        {
          path: 'monitor/export',
          name: 'MonitorDataExport',
          component: () => import('@/views/MonitorDataExport.vue'),
          meta: { titleKey: 'routes.monitorExport' },
        },
        {
          path: 'webhooks',
          name: 'WebhookList',
          component: () => import('@/views/WebhookList.vue'),
          meta: { titleKey: 'routes.webhooks' },
        },
        {
          path: 'webhooks/new',
          name: 'WebhookCreate',
          component: () => import('@/views/WebhookForm.vue'),
          meta: { titleKey: 'routes.webhookCreate' },
        },
        {
          path: 'webhooks/:id/edit',
          name: 'WebhookEdit',
          component: () => import('@/views/WebhookForm.vue'),
          props: true,
          meta: { titleKey: 'routes.webhookEdit' },
        },
        {
          path: 'webhooks/:id/deliveries',
          name: 'WebhookDeliveries',
          component: () => import('@/views/WebhookDeliveries.vue'),
          props: true,
          meta: { titleKey: 'routes.webhookDeliveries' },
        },
        {
          path: 'settings/grafana',
          name: 'GrafanaSettings',
          component: () => import('@/views/GrafanaSettings.vue'),
          meta: { titleKey: 'layout.grafana_settings' },
        },
        {
          path: 'grafana/dashboards',
          name: 'GrafanaDashboards',
          component: () => import('@/views/GrafanaDashboards.vue'),
          meta: { titleKey: 'layout.grafana_dashboards' },
        },
        {
          path: 'settings/oauth2',
          name: 'OAuth2Apps',
          component: () => import('@/views/OAuth2Apps.vue'),
          meta: { titleKey: 'layout.oauth2_apps' },
        },
        {
          path: 'settings/plugins',
          name: 'PluginList',
          component: () => import('@/views/PluginList.vue'),
          meta: { titleKey: 'layout.plugins' },
        },
        {
          path: 'monitors',
          name: 'UptimeMonitors',
          component: () => import('@/views/UptimeMonitors.vue'),
          meta: { titleKey: 'routes.uptimeMonitors' },
        },
        {
          path: 'heartbeats',
          name: 'Heartbeats',
          component: () => import('@/views/Heartbeats.vue'),
          meta: { titleKey: 'routes.heartbeats' },
        },
        {
          path: 'dashboard-tv',
          name: 'DashboardTV',
          component: () => import('@/views/DashboardTV.vue'),
          meta: { titleKey: 'routes.dashboardTV' },
        },
        {
          path: 'notifications',
          name: 'Notifications',
          component: () => import('@/views/Notifications.vue'),
          meta: { titleKey: 'routes.notifications' },
        },
        {
          path: 'templates',
          name: 'Templates',
          component: () => import('@/views/Templates.vue'),
          meta: { titleKey: 'routes.templates' },
        },
        {
          path: 'users',
          name: 'Users',
          component: () => import('@/views/Users.vue'),
          meta: { titleKey: 'routes.users' },
        },
        {
          path: 'audit',
          name: 'Audit',
          component: () => import('@/views/Audit.vue'),
          meta: { titleKey: 'routes.audit' },
        },
        {
          path: 'system',
          name: 'System',
          component: () => import('@/views/System.vue'),
          meta: { titleKey: 'routes.system' },
        },
        {
          path: 'api-keys',
          name: 'ApiKeys',
          component: () => import('@/views/ApiKeys.vue'),
          meta: { titleKey: 'routes.apiKeys' },
        },
        {
          path: 'settings/security',
          name: 'SecuritySettings',
          component: () => import('@/views/SecuritySettings.vue'),
          meta: { titleKey: 'routes.security' },
        },
        {
          path: 'license',
          name: 'License',
          component: () => import('@/views/License.vue'),
          meta: { titleKey: 'routes.license' },
        },
        {
          path: 'feature-flags',
          name: 'FeatureFlags',
          component: () => import('@/views/FeatureFlags.vue'),
          meta: { titleKey: 'routes.featureFlags' },
        },
        {
          path: 'trial',
          name: 'Trial',
          component: () => import('@/views/Trial.vue'),
          meta: { titleKey: 'routes.trial' },
        },
      ],
    },
  ],
})

export default router
